# experiment
exp: logs/w_outside_visual/all_modalities/lstm
alg: lstm

# train
data_dir: VisualTactileData_all
data_split: 0.7
epoch: 80
batch_size: 32
random_seed: 4
num_workers: 4
device: 'cuda:1'
val_interval: 2

optimizer: Adam #'SGD'
lr: 5e-5
momentum: 0.9

scheduler: StepLR
period: 10
gamma: 0.9

loss: CrossEntropyLoss

# data
img_size: 128
patch_size: 16
in_channels: 3
visual_modality: {'1': 'v', '2': 'v', '3': 'v'}
random_visual: True
tactile_modality: {'v': 'vt', 't': 't'}
num_classes: 12

##  network
# Convlayer sustitute
out_channels: 64
kernel_size: 7
stride: 1
padding: 3
bias: False
# feature dim
feature_dim: 384