# experiment
exp: logs/wo_outside_visual/tactile_only/lstm
alg: lstm

# train
data_dir: VisualTactileData_segT
data_split: 0.7
epoch: 150
batch_size: 32
random_seed: 0
num_workers: 4
device: 'cuda:1'
val_interval: 3

optimizer: Adam #'SGD'
lr: 1e-5
momentum: 0.9

scheduler: StepLR
period: 30
gamma: 0.9

loss: CrossEntropyLoss

# data
img_size: 128
patch_size: 16
in_channels: 3
visual_modality: {}
random_visual: True
tactile_modality: {'t': 't'}
num_classes: 12

##  network
# Convlayer sustitute
out_channels: 64
kernel_size: 7
stride: 1
padding: 3
bias: False
# feature dim
feature_dim: 384