# experiment
exp: logs/wo_outside_visual/tactile_only/mmvtt
alg: MMVTT

# train
data_dir: VisualTactileData_all
data_split: 0.7
epoch: 150
batch_size: 32
random_seed: 0
num_workers: 4
device: 'cuda:1'
val_interval: 3

optimizer: Adam #'SGD'
lr: 1e-5
momentum: 0.9

scheduler: StepLR
period: 30
gamma: 0.9

loss: CrossEntropyLoss

# data
img_size: 128
patch_size: 16
in_chans: 3
visual_modality: {}
random_visual: True
tactile_modality: {'t':'t'}

## network
# resnet
out_channels: 64
kernel_size: 7
stride: 1
padding: 3
bias: False
# attention
embed_dim: 384
depth: 1
num_heads: 4
mlp_ratio: 4.
qkv_bias: False
qk_scale:
drop_rate: 0.
attn_drop_rate: 0.
drop_path_rate: 0.1