# experiment
exp: logs/lstms/lstm

# train
data_dir: VisualTactileData_raw
data_split: 0.8
epoch: 1000
batch_size: 32
random_seed: 128
num_workers: 4
device: 'cuda:1'
val_interval: 10

optimizer: Adam #'SGD'
lr: 0.0001
momentum: 0.9

scheduler: StepLR
period: 100
gamma: 0.9

loss: CrossEntropyLoss

# data
img_size: 128
patch_size: 16
in_channels: 3
visual_modality: {}
random_visual: True
tactile_modality: {'t': 'vt'}
num_classes: 12

##  network
# Convlayer sustitute
out_channels: 64
kernel_size: 7
stride: 1
padding: 3
bias: False
# feature dim
feature_dim: 384