# experiment
exp: logs/VTT/seg_T/tactile_only
alg: MMVTT

# train
data_dir: VisualTactileData_segT
data_split: 0.7
epoch: 1000
batch_size: 32
random_seed: 0
num_workers: 4
device: 'cuda:1'
val_interval: 10

optimizer: Adam #'SGD'
lr: 0.0001
momentum: 0.9

scheduler: StepLR
period: 100
gamma: 0.9

loss: CrossEntropyLoss

# data
img_size: 128
patch_size: 16
in_chans: 3
visual_modality: {}
random_visual: True
tactile_modality: {'t':'t'}

# network
visual_embed_mapping: {}  # in above order, e.g. 0-> '1', 1-> '2', 2 -> '3'
tactile_embed_mapping: {0: [0]}
embed_dim: 384
depth: 1
num_heads: 4
mlp_ratio: 4.
qkv_bias: False
qk_scale:
drop_rate: 0.
attn_drop_rate: 0.
drop_path_rate: 0.1