# experiment
exp: logs/segT/visual_tactile 

# train
data_dir: VisualTactileData_segT
data_split: 0.8
epoch: 1000
batch_size: 32
random_seed: 1
num_workers: 4
device: 'cuda:1'

optimizer: Adam #'SGD'
lr: 0.0001
momentum: 0.9

scheduler: StepLR
period: 100
gamma: 0.9

loss: CrossEntropyLoss

# data
img_size: 128
crop_size: 300
patch_size: 16
in_chans: 3
visual_modality: ['1', '2', '3']
random_visual: True
tactile_modality: True
tactile_modality: []

# network
embed_dim: 384
depth: 6
num_heads: 8
mlp_ratio: 4.
qkv_bias: False
qk_scale:
drop_rate: 0.
attn_drop_rate: 0.
drop_path_rate: 0.1




